"use client";

import Link from "next/link";
import { ThemeToggle } from "@/components/theme-toggle";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-stone-50 dark:bg-[#111]">
      <nav className="bg-white/80 dark:bg-[#111]/80 backdrop-blur-md border-b border-stone-200/60 dark:border-white/5">
        <div className="max-w-4xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="font-extrabold text-lg">SoundSnap</Link>
          <ThemeToggle />
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-2xl font-extrabold tracking-tight mb-8">Terms of Service</h1>
        <div className="space-y-6 text-sm text-stone-500 dark:text-stone-400 leading-relaxed">
          <p>Last updated: March 2026</p>
          <h2 className="text-base font-bold text-stone-900 dark:text-white">1. Acceptance of Terms</h2>
          <p>By using SoundSnap, you agree to these Terms of Service. If you do not agree, please do not use our service.</p>
          <h2 className="text-base font-bold text-stone-900 dark:text-white">2. Service Description</h2>
          <p>SoundSnap provides AI-powered audio generation for videos through an Adobe Express add-on and web dashboard. The service uses credits for each generation.</p>
          <h2 className="text-base font-bold text-stone-900 dark:text-white">3. Credits and Payments</h2>
          <p>Credits are purchased through our payment provider (DodoPayments). Credits do not expire. All purchases are final and non-refundable unless required by applicable law. Each audio generation costs 1 credit.</p>
          <h2 className="text-base font-bold text-stone-900 dark:text-white">4. Acceptable Use</h2>
          <p>You agree not to use SoundSnap for illegal purposes, to generate harmful content, or to attempt to circumvent our credit system. You are responsible for the content you upload and generate.</p>
          <h2 className="text-base font-bold text-stone-900 dark:text-white">5. Intellectual Property</h2>
          <p>You retain ownership of your uploaded videos. Audio generated by SoundSnap is licensed to you for use in your projects. SoundSnap and its branding are our intellectual property.</p>
          <h2 className="text-base font-bold text-stone-900 dark:text-white">6. Limitation of Liability</h2>
          <p>SoundSnap is provided &quot;as is&quot; without warranties. We are not liable for any indirect, incidental, or consequential damages arising from your use of the service.</p>
          <h2 className="text-base font-bold text-stone-900 dark:text-white">7. Changes to Terms</h2>
          <p>We may update these terms at any time. Continued use of SoundSnap after changes constitutes acceptance of the new terms.</p>
          <h2 className="text-base font-bold text-stone-900 dark:text-white">8. Contact</h2>
          <p>For questions about these terms, contact us at support@soundsnap.app.</p>
        </div>
      </div>
    </div>
  );
}
